#! /usr/bin/env python
# -*- coding: utf-8 -*-

'''
    Show GoodCrypto web status
    
    This command runs on the host system.
    
    Copyright 2014 GoodCrypto
    Last modified: 2014-08-29
'''

# delete in python 3
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

import os.path, sh

import syr.cli

from goodcrypto.test.utils import run_ssh_command

run_ssh_command(
        'root@127.0.0.1:{}'.format(VM_CERT_PATH),
        HOST_DIR,
        scp=True)

