#! /usr/bin/env python
'''
    rc.local for GoodCrypto Web

    Copyright 2015 GoodCrypto
    Last modified: 2015-11-22
'''
import os, sh, sys, time
from traceback import format_exc

# set up django early
from goodcrypto.utils import gc_django
gc_django.setup()

from syr.log import get_log
from syr.user import sudo
from syr.process import is_program_running
from goodcrypto.utils.persistence import make_persistent, PERSISTENT_DIR


log = get_log('/var/log/rc.local.log')


def start_web_app():

    def wait_for_web_proxy():
        ''' Make sure the web proxy started '''

        MAXWAIT = 10 # seconds

        wait = 0
        while (not is_program_running(WEB_FILTER_PROGRAM)) and (wait < MAXWAIT):
            time.sleep(1)
            wait = wait + 1
        log('web server started in {} seconds: {}'.format(wait, is_program_running(WEB_FILTER_PROGRAM)))

    GC_DIR = '/var/local/projects/goodcrypto'
    SRC_DIR = os.path.join(GC_DIR, 'server/src')
    DATA_DIR = os.path.join(GC_DIR, 'server/data')
    DB_DIR = os.path.join(DATA_DIR, 'db')
    WEB_PERSISTENT_DIR = os.path.join(DATA_DIR, 'web')
    WEB_SECURITY_DIR = os.path.join(WEB_PERSISTENT_DIR, 'security')
    WEB_CONFIGURED_FLAG = os.path.join(PERSISTENT_DIR, '.web.configured')
    WEB_FILTER_PROGRAM = 'web/filters.py'

    log('starting web proxy')
    # the web program uses web/__main__.py, and
    # web/__main__.py does not launch filters.py well right now
    # goodcrypto-web start
    # filters.py does the actual work
    #with sudo('goodcrypto'):
    #    sh.python(os.path.join(SRC_DIR, WEB_FILTER_PROGRAM), _bg=True)
    sh.goodcrypto_web('start')
    wait_for_web_proxy()

    log('started web app')

def main():

    start_web_app()

if __name__ == '__main__':
    try:
        main()
    except Exception as exc:
        log(format_exc())
        raise

