#! /usr/bin/env python
# -*- coding: utf-8 -*-

'''
    Run GoodCrypto web control in chroot
    
    Copyright 2014 GoodCrypto
    Last modified: 2014-09-01
'''

# delete in python 3
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

import sh, os.path

import syr.utils
from syr.log import get_log

log = get_log()

from dbuild.configs.shared import Settings as SharedSettings

GOODCRYPTO_WEB = 'goodcrypto-web'
THIS_DIR = os.path.dirname(os.path.realpath(__file__))
WEB_SCRIPT = os.path.join(THIS_DIR, GOODCRYPTO_WEB)
WEB_CHROOT_DIR = os.path.join(SharedSettings.GOODCRYPTO_CHROOT_DIR, 'web')

if os.path.exists(WEB_CHROOT_DIR):

    chroot_script = os.path.join(
        WEB_CHROOT_DIR,
        syr.utils.ltrim(WEB_SCRIPT, '/'))
        
    if os.path.exists(chroot_script):
        args = sys.argv[1:]
        print('running chr "{}" "{}" {}'.format(
            WEB_CHROOT_DIR, 
            WEB_SCRIPT,
            repr(*args)))
        try:
            sh.chr(WEB_CHROOT_DIR, WEB_SCRIPT, *args)
        except sh.ErrorReturnCode as sh_error:
            print(sh_error.full_cmd)
            print(sh_error.stdout)
            print(sh_error.stderr)
            raise
    else:
        print('error in {}: missing {}'.format(
            WEB_CHROOT_DIR, 
            WEB_SCRIPT))
        
else:
    print('missing {}'.format(WEB_CHROOT_DIR))


"""
#! /bin/bash

#   run goodcrypto web control in chroot

#   Copyright 2014 GoodCrypto
#   Last modified: 2014-09-01

CHROOT_DIR=/var/local/chroot/goodcrypto/web
# CHROOT_DIR=/var/local/projects/goodcrypto/server/data/chroot/goodcrypto/web
WEB_DIR=/var/local/projects/goodcrypto/server/src/web/tools/web

if [ -e $CHROOT_DIR ] ; then
    if [ -e $CHROOT_DIR$WEB_DIR ] ; then
        chr $CHROOT_DIR $WEB_DIR "$@"
    else
        echo error in $CHROOT_DIR
        echo "    " missing $WEB_DIR
    fi
else
    echo missing $CHROOT_DIR
fi
"""
