#! /usr/bin/env python3
# -*- coding: utf-8 -*-

'''
    Show GoodCrypto webfirewall status
    
    This command runs on the host system.
    
    Copyright 2014-2016 GoodCrypto
    Last modified: 2016-09-05
'''

import sys
IS_PY2 = sys.version_info[0] == 2

if IS_PY2:
    reload(sys)
    sys.setdefaultencoding('utf-8')

import os.path, sh

import syr.cli

try:
    from goodcrypto.test.utils import run_ssh_command
except:
    from webfirewall.goodcrypto.test.utils import run_ssh_command
    
run_ssh_command(
        'root@127.0.0.1:{}'.format(VM_CERT_PATH),
        HOST_DIR,
        scp=True)

