#! /usr/bin/env python3
'''
    rc.local for GoodCrypto Webfirewall

    Copyright 2015-2016 GoodCrypto
    Last modified: 2016-09-05
'''
import os, sh, sys, time
from traceback import format_exc

# set up django early
try:
    from goodcrypto.utils import gc_django
except:
    from webfirewall.goodcrypto.utils import gc_django
gc_django.setup()

from syr.log import get_log
from syr.user import sudo
from syr.process import is_program_running
try:
    from goodcrypto.utils.persistence import make_persistent, PERSISTENT_DIR
except:
    from webfirewall.goodcrypto.utils.persistence import make_persistent, PERSISTENT_DIR


log = get_log('/var/log/rc.local.log')


def start_web_firewall():

    def wait_for_web_proxy():
        ''' Make sure the web proxy started '''

        MAXWAIT = 10 # seconds

        wait = 0
        while (not is_program_running(WEB_FILTER_PROGRAM)) and (wait < MAXWAIT):
            time.sleep(1)
            wait = wait + 1
        log('web firewall started in {} seconds: {}'.format(wait, is_program_running(WEB_FILTER_PROGRAM)))

    GC_DIR = '/var/local/projects/goodcrypto'
    SRC_DIR = os.path.join(GC_DIR, 'server/src')
    DATA_DIR = os.path.join(GC_DIR, 'server/data')
    DB_DIR = os.path.join(DATA_DIR, 'db')
    WEB_PERSISTENT_DIR = os.path.join(DATA_DIR, 'webfirewall')
    WEB_SECURITY_DIR = os.path.join(WEB_PERSISTENT_DIR, 'security')
    WEB_CONFIGURED_FLAG = os.path.join(PERSISTENT_DIR, '.webfirewall.configured')
    WEB_FILTER_PROGRAM = 'webfirewall/filters.py'

    log('starting web firewall')
    # the web program uses webfirewall/__main__.py, and
    # webfirewall/__main__.py does not launch filters.py well right now
    # goodcrypto-web start
    # filters.py does the actual work
    #with sudo('goodcrypto'):
    #    sh.python(os.path.join(SRC_DIR, WEB_FILTER_PROGRAM), _bg=True)
    sh.goodcrypto_webfirewall('start')
    wait_for_web_proxy()

    log('started web firewall')

def main():

    start_web_firewall()

if __name__ == '__main__':
    try:
        main()
    except Exception as exc:
        log(format_exc())
        raise

